name: Auto Build
on: 
  push:
    branches: [master,main]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/build.yml'
      - '**.md'
      - '.gitignore'
  pull_request:
    branches: [master,main]

jobs:
  auto-build:
    name: Auto Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build mod
        uses: ./.github/actions/build

      - name: Upload mod as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: 'bin/**'
